### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attributes' of null

### ISSUE THREAD

**Issue by WuglyakBolgoink** [rajexcited/AngularJS-Birbal#2]
I use angular.bootstrap, so I have always error:
```
angularinspector.js:136 Uncaught TypeError: Cannot read property 'attributes' of null
```

See: https://github.com/Linkurious/angular-performance/issues/23

**Comment by rajexcited** [comment]
As of current architecture, this extension supports bootstrapping angular only through ngApp directive. You are seeing this error because ngApp directive is not specified. 
I will think about it and will enhance extension to detect angular.bootstrap too.

**Comment by WuglyakBolgoink** [comment]
@rajexcited 
thank you!

**Comment by rajexcited** [comment]
Changed architecture to detect manual bootstrap now.  Check out version 0.0.8 of the extension.
