### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by WuglyakBolgoink** [rajexcited/AngularJS-Birbal#3]
```
AngularJS Birbal

Version: 0.0.12
Aktualisiert: 2. Januar 2017
```

if  FALSE - error, if TRUE - ok
```
// https://docs.angularjs.org/guide/production#disabling-debug-data
        $compileProvider.debugInfoEnabled(false);
```

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at inspectAngular (<anonymous>:1:14712)
VM44:1 Uncaught TypeError: Cannot read property 'split' of undefined
    at inspectAngular (<anonymous>:1:14712)
```

in 
```
sendDependencyTree(msg.ngModule.split(","))}else{window.name=window.name.replace(/^NG_DEFER_BOOTSTRAP!/,"")}
```

![bildschirmfoto 2017-01-18 um 11 44 43](https://cloud.githubusercontent.com/assets/2271337/22061039/8a2a96da-dd73-11e6-8ea9-f9c5fba2ba62.png)

**Comment by rajexcited** [comment]
Main reason is strict Di changes in new angular version which forces dependency to be injected in array style. This has been addressed in current changes and will be resolved in next release.

**Comment by rajexcited** [comment]
New version has resolution to this issue.
