### ISSUE TITLE
Error on "Start perf analyze"

### ISSUE THREAD

**Issue by WuglyakBolgoink** [rajexcited/AngularJS-Birbal#5]
```
AngularJS Birbal

Version: 0.0.12
Aktualisiert: 2. Januar 2017
```

![bildschirmfoto 2017-01-18 um 11 50 05](https://cloud.githubusercontent.com/assets/2271337/22061239/5c12f264-dd74-11e6-8fce-3ffbff27fbdc.png)

**Comment by rajexcited** [comment]
This is not running through chrome-extension.
