### ISSUE TITLE
Problem since update

### ISSUE THREAD

**Issue by Angst003** [rajexcited/AngularJS-Birbal#6]
Hi,

I **LOVE** this extension but since the update last week it stopped working. My Angular application always get ResponseError when it is enabled and everything works fine when I disable it.

Thanks,
Pascal

**Comment by rajexcited** [comment]
What version of angular API are you using?

**Comment by Angst003** [comment]
1.3.3

**Comment by Angst003** [comment]
I upgrade to 1.5.8 and everything works fine now.

**Comment by rajexcited** [comment]
Issue has been fixed for older angular versions. As new version of angular has feature of info to module and which I was using in mocking AJAX calls. But with tweaks, it should work for any angular version. Checkout new extension version v0.0.15

**Comment by Angst003** [comment]
Everything works fine with versions 1.3.3 and 1.5.8 of AngularJS. Good job, thank you very much.
